<link rel="stylesheet" href="../templates/loadingView/css/style.css" />
<link rel="stylesheet" href="../templates/header/css/style.css" />
<link rel="stylesheet" href="../templates/footer/css/style.css" />
<link rel="stylesheet" href="../templates/logo/css/style.css" />
<link rel="stylesheet" href="../templates/productPopup/css/style.css" />
<link rel="stylesheet" href="../templates/diamondOnHand/css/style.css" />
<link rel="stylesheet" href="../libraries/noUiSlider.10.0.0/nouislider.css" />
<link rel="stylesheet" href="../templates/popup/css/style.css" />
<link rel="stylesheet" href="../templates/menu/css/style.css" />
<link rel="stylesheet" href="../templates/miniCart/css/style.css" />
<link rel="stylesheet" href="../templates/miniBidsList/css/style.css" />
<link rel="stylesheet" href="../templates/wishList/css/style.css" />
<link rel="stylesheet" href="../templates/compareMaster/css/style.css" />
<link rel="stylesheet" href="../templates/recentlyViewed/css/style.css" />
<link rel="stylesheet" href="../templates/smartSearch/css/style.css" />
<link rel="stylesheet" href="../css/style.css" />
<link rel="stylesheet" href="../css/1.12.1-jquery-ui.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<link href="https://fonts.googleapis.com/css?family=Assistant:200,300,400,600,700,800" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.2.0/css/bootstrap-slider.min.css" />